name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        pre-shared-key: ${{ secrets.VPN_PSK }}
        ip-address: ${{ secrets.VPN_IPADDRESS }}
        username: ${{ secrets.VPN_USERNAME }}
        password: ${{ secrets.VPN_PASSWORD }}
    - run: sudo tail /var/log/syslog
